import type { TathyaConfig } from '../config.js';

/** Published path (inside `output.dir`) of the shared support module every spec imports. */
export const SUPPORT_MODULE_PATH = 'support/tathya.ts';

/** Import specifier for the support module from a spec in a category folder (`<dir>/<file>`). */
export const SUPPORT_IMPORT = '../support/tathya.js';

export const GENERATED_HEADER = '// Generated by `tt generate` — do not edit; this file is overwritten on every run.\n';

/**
 * Source of `support/tathya.ts`: the one place the generated suite keeps its login helpers,
 * fixtures, and oracle helpers. Specs stay short and read as scenarios; everything app-specific
 * (credentials, login path, error indicator, reset hook) is pinned here from the config.
 */
export function supportModuleSource(config: Pick<TathyaConfig, 'auth' | 'oracle' | 'hooks'>): string {
  const credentials = Object.fromEntries(config.auth.roles.map((role) => [role.name, { username: role.username, password: role.password }]));
  const reset = config.hooks?.reset ?? null;
  return `${GENERATED_HEADER}import { test as base, expect, type Page, type Response } from '@playwright/test';

export { expect };

/** Credentials per role, from tathya.config.yaml. */
export const roleCredentials = ${JSON.stringify(credentials, null, 2)} as const;
export type Role = keyof typeof roleCredentials;

const loginPath = ${JSON.stringify(config.auth.loginPath)};
const errorSelector = ${JSON.stringify(config.oracle.errorSelector)};
const resetHook: { method: 'POST' | 'GET' | 'DELETE'; path: string } | null = ${JSON.stringify(reset)};

export type App = {
  /** Reset app data (when the app has a reset hook), drop the session, and log in as \`role\`. */
  loginAs(role: Role): Promise<void>;
  /** Read-only runs: reuse the project's stored session when it is still valid, else log in — never reset. */
  ensureLoggedIn(role: Role): Promise<void>;
  /** Call the app's reset hook, if one is configured. */
  resetData(): Promise<void>;
};

/**
 * \`test\` with two extra fixtures: \`role\` — the role of the current Playwright project
 * (\`admin-chromium\` → \`admin\`), used to gate role-specific groups — and \`app\`, the
 * authenticated-session helper.
 */
export const test = base.extend<{ role: string; app: App }>({
  role: async ({}, use, testInfo) => {
    await use(testInfo.project.name.split('-')[0] ?? '');
  },
  app: async ({ page }, use) => {
    await use({
      loginAs: (role) => loginAs(page, role),
      ensureLoggedIn: (role) => ensureLoggedIn(page, role),
      resetData: () => resetAppData(page),
    });
  },
});

type LoginLocator = { strategy: 'testid' | 'role' | 'label' | 'placeholder' | 'id' | 'name' | 'css'; value: string };
type LoginControls = { username: LoginLocator; password: LoginLocator; submit: LoginLocator };

export async function resetAppData(page: Page): Promise<void> {
  if (!resetHook) return;
  await page.request.fetch(resetHook.path, { method: resetHook.method });
}

export async function loginAs(page: Page, role: Role): Promise<void> {
  await resetAppData(page);
  await page.context().clearCookies();
  const credentials = roleCredentials[role];
  await performLogin(page, credentials.username, credentials.password);
  await assertLoggedIn(page);
}

/**
 * Open the login page: an app that still has a valid session (the project's storageState) sends
 * an authenticated visitor elsewhere, so nothing more to do; otherwise log in. No reset hook.
 */
export async function ensureLoggedIn(page: Page, role: Role): Promise<void> {
  await page.goto(loginPath);
  await page.waitForLoadState('domcontentloaded').catch(() => undefined);
  const expectedLoginPath = new URL(loginPath, 'http://tathyatest.local').pathname;
  const passwordField = page.locator('input[type="password"]').first();
  if (new URL(page.url()).pathname !== expectedLoginPath || !(await passwordField.isVisible().catch(() => false))) return;
  const credentials = roleCredentials[role];
  await performLogin(page, credentials.username, credentials.password);
  await assertLoggedIn(page);
}

export async function performLogin(page: Page, username: string, password: string): Promise<void> {
  await page.goto(loginPath);
  const controls = await inferLoginControls(page);
  await loginLocator(page, controls.username).fill(username);
  await loginLocator(page, controls.password).fill(password);
  const beforePath = new URL(page.url()).pathname;
  await Promise.all([
    page.waitForURL((url) => url.pathname !== beforePath, { timeout: 5000 }).catch(() => undefined),
    loginLocator(page, controls.submit).click(),
  ]);
  await page.waitForLoadState('networkidle').catch(() => undefined);
}

/** Logged in = we left the login page, or the password field is gone. */
export async function assertLoggedIn(page: Page): Promise<void> {
  const expectedLoginPath = new URL(loginPath, 'http://tathyatest.local').pathname;
  if (new URL(page.url()).pathname !== expectedLoginPath) return;
  await expect(page.locator('input[type="password"], input[autocomplete="current-password"], input[name*="password"], input[id*="password"], input[placeholder*="Password"]').first()).not.toBeVisible();
}

/** A rejected login shows the app's error indicator. */
export async function assertLoginRejected(page: Page): Promise<void> {
  await expect(page.locator(errorSelector).first()).toBeVisible();
}

/** A small in-memory file of the given MIME type for \`setInputFiles\` (no fixture files on disk). */
export function uploadFixture(mimeType: string): { name: string; mimeType: string; buffer: Buffer } {
  const extension = { 'image/png': 'png', 'image/jpeg': 'jpg', 'image/gif': 'gif', 'application/pdf': 'pdf', 'text/plain': 'txt', 'text/csv': 'csv', 'application/json': 'json' }[mimeType] ?? 'bin';
  const content = mimeType === 'image/png'
    ? Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mNkYPhfDwAChwGA60e6kgAAAABJRU5ErkJggg==', 'base64')
    : mimeType === 'application/pdf'
      ? Buffer.from('%PDF-1.4\\n1 0 obj<</Type/Catalog>>endobj\\ntrailer<</Root 1 0 R>>\\n%%EOF\\n')
      : Buffer.from('TathyaTest upload fixture\\n');
  return { name: 'tathyatest-upload.' + extension, mimeType, buffer: content };
}

/**
 * A GET (search/filter) form round-trips its fields into the URL: every submitted value must
 * come back in the query string (an empty value may be omitted by the app).
 */
export async function expectQueryEcho(page: Page, params: Record<string, string>): Promise<void> {
  await page.waitForLoadState('domcontentloaded').catch(() => undefined);
  const query = new URL(page.url()).searchParams;
  for (const [key, value] of Object.entries(params)) {
    const actual = query.get(key);
    if (value === '') expect(actual === null || actual === '').toBe(true);
    else expect(actual, 'query parameter ' + key).toBe(value);
  }
  await expectNoServerError(page);
}

/**
 * A fieldless state-change form (toggle done/undone, archive, publish) proves it worked by its
 * own submit control reading differently afterwards; a control that disappeared (the row moved
 * to another list) is accepted too.
 */
export async function expectStateFlipped(page: Page, formSelector: string, before: string | null): Promise<void> {
  await page.waitForLoadState('domcontentloaded').catch(() => undefined);
  const control = page.locator(formSelector).first();
  if (before && (await control.count()) > 0) await expect(control).not.toContainText(before);
  await expectNoServerError(page);
}

/** The page settled and shows no server-error text. */
export async function expectNoServerError(page: Page): Promise<void> {
  await page.waitForLoadState('domcontentloaded').catch(() => undefined);
  await page.waitForLoadState('networkidle').catch(() => undefined);
  await expect(page.locator('body')).not.toContainText(/500|server error|exception/i);
}

/**
 * Allowed = a healthy (< 400) document response, OR — because SPA hosts serve deep links with an
 * error status while the client router still renders the page — staying on the route with
 * interactive content rendered. A genuine error page fails both arms.
 */
export async function expectRouteAllowed(page: Page, response: Response | null, routePath: string): Promise<void> {
  const status = response?.status() ?? 200;
  if (status >= 400) {
    await page.waitForLoadState('networkidle').catch(() => undefined);
    expect(new URL(page.url()).pathname).toBe(routePath);
    expect(await page.locator('a, button, form, select, input').count()).toBeGreaterThan(0);
  }
  await expectNoServerError(page);
}

/**
 * Blocked = a direct denial status, or — since page.goto resolves redirect chains — a 2xx on a
 * DIFFERENT path; either way the body is graceful.
 */
export async function expectRouteBlocked(page: Page, response: Response | null, blockedPath: string): Promise<void> {
  const status = response?.status() ?? 200;
  if (status < 400) {
    expect(new URL(page.url()).pathname).not.toBe(blockedPath);
  } else {
    expect([401, 403, 404]).toContain(status);
  }
  await expectNoServerError(page);
}

function loginLocator(page: Page, locator: LoginLocator) {
  switch (locator.strategy) {
    case 'testid':
      return page.getByTestId(locator.value);
    case 'role': {
      const [role, ...nameParts] = locator.value.split(':');
      const name = nameParts.join(':');
      return name ? page.getByRole(role as Parameters<typeof page.getByRole>[0], { name }) : page.getByRole(role as Parameters<typeof page.getByRole>[0]);
    }
    case 'label':
      return page.getByLabel(locator.value, { exact: true });
    case 'placeholder':
      return page.getByPlaceholder(locator.value);
    case 'id':
      return page.locator('#' + cssEscape(locator.value));
    case 'name':
      return page.locator('[name="' + cssEscape(locator.value) + '"]');
    case 'css':
      return page.locator(locator.value);
  }
}

/** Score the login page's inputs/buttons the same way the crawler does (see generator/src/login.ts). */
export async function inferLoginControls(page: Page): Promise<LoginControls> {
  await page.waitForLoadState('domcontentloaded').catch(() => undefined);
  return page.evaluate(() => {
    type Candidate = {
      tag: 'input' | 'button';
      type: string;
      name: string;
      id: string;
      placeholder: string;
      autocomplete: string;
      ariaLabel: string;
      dataAttr: string;
      dataValue: string;
      text: string;
      value: string;
    };
    const attr = (el: Element, name: string): string => el.getAttribute(name) ?? '';
    const text = (el: Element): string => (el.textContent ?? '').replace(/\\s+/g, ' ').trim();
    const candidateText = (candidate: Candidate): string => [
      candidate.type,
      candidate.name,
      candidate.id,
      candidate.placeholder,
      candidate.autocomplete,
      candidate.ariaLabel,
      candidate.dataValue,
      candidate.text,
      candidate.value,
    ].join(' ').toLowerCase();
    const stableId = (value: string): boolean => value.length > 0 && !/[0-9a-f]{8,}|:/.test(value);
    const cssEscape = (value: string): string => {
      const escaper = (globalThis as typeof globalThis & { CSS?: { escape?: (v: string) => string } }).CSS?.escape;
      return escaper ? escaper(value) : value.replace(/["\\\\]/g, '\\\\$&');
    };
    const inputCandidate = (input: HTMLInputElement): Candidate => ({
      tag: 'input',
      type: (input.type || 'text').toLowerCase(),
      name: input.name,
      id: input.id,
      placeholder: input.placeholder,
      autocomplete: input.autocomplete,
      ariaLabel: attr(input, 'aria-label'),
      dataAttr: attr(input, 'data-test') ? 'data-test' : attr(input, 'data-testid') ? 'data-testid' : '',
      dataValue: attr(input, 'data-test') || attr(input, 'data-testid'),
      text: '',
      value: input.value,
    });
    const buttonCandidate = (button: HTMLButtonElement | HTMLInputElement): Candidate => ({
      tag: button.tagName.toLowerCase() === 'button' ? 'button' : 'input',
      type: (attr(button, 'type') || (button instanceof HTMLButtonElement ? 'submit' : 'text')).toLowerCase(),
      name: attr(button, 'name'),
      id: attr(button, 'id'),
      placeholder: attr(button, 'placeholder'),
      autocomplete: attr(button, 'autocomplete'),
      ariaLabel: attr(button, 'aria-label'),
      dataAttr: attr(button, 'data-test') ? 'data-test' : attr(button, 'data-testid') ? 'data-testid' : '',
      dataValue: attr(button, 'data-test') || attr(button, 'data-testid'),
      text: button instanceof HTMLInputElement ? '' : text(button),
      value: button instanceof HTMLInputElement ? button.value : attr(button, 'value'),
    });
    const locatorFor = (candidate: Candidate | undefined, kind: 'username' | 'password' | 'submit'): LoginLocator => {
      if (!candidate) {
        if (kind === 'submit') return { strategy: 'css', value: 'button[type="submit"], input[type="submit"], button:not([type])' };
        return { strategy: 'css', value: kind === 'username' ? 'input:not([type="hidden"]):not([type="password"])' : 'input[type="password"]' };
      }
      if (candidate.dataAttr && candidate.dataValue) return { strategy: 'css', value: '[' + candidate.dataAttr + '="' + cssEscape(candidate.dataValue) + '"]' };
      if (candidate.placeholder) return { strategy: 'placeholder', value: candidate.placeholder };
      if (stableId(candidate.id)) return { strategy: 'id', value: candidate.id };
      if (candidate.name) return { strategy: 'name', value: candidate.name };
      const buttonText = candidate.text || candidate.value;
      if (candidate.tag === 'button' && buttonText) return { strategy: 'role', value: 'button:' + buttonText };
      return { strategy: 'css', value: candidate.tag === 'button' ? 'button' : 'input' };
    };
    const inputs = Array.from(document.querySelectorAll<HTMLInputElement>('input'))
      .map(inputCandidate)
      .filter((input) => !['hidden', 'submit', 'button', 'reset', 'image', 'file'].includes(input.type));
    const buttons = [
      ...Array.from(document.querySelectorAll<HTMLButtonElement>('button')).map(buttonCandidate),
      ...Array.from(document.querySelectorAll<HTMLInputElement>('input[type="submit"], input[type="button"]')).map(buttonCandidate),
    ];
    const username = inputs
      .map((input) => {
        const haystack = candidateText(input);
        let score = 0;
        if (input.type === 'email') score += 100;
        if (input.autocomplete.toLowerCase() === 'username') score += 90;
        if (input.autocomplete.toLowerCase() === 'email') score += 80;
        if (/(email|username|user|account|identifier|handle)/.test(haystack)) score += 50;
        return { input, score };
      })
      .sort((a, b) => b.score - a.score)[0]?.input ?? inputs[0];
    const password = inputs
      .map((input) => {
        const haystack = candidateText(input);
        let score = 0;
        if (input.type === 'password') score += 100;
        if (/(password|passcode|pin)/.test(haystack)) score += 50;
        return { input, score };
      })
      .sort((a, b) => b.score - a.score)[0]?.input ?? inputs.find((input) => input !== username) ?? inputs[1] ?? inputs[0];
    const submit = buttons
      .map((button) => {
        const haystack = candidateText(button);
        let score = 0;
        if (button.dataValue) score += 100;
        if (button.tag === 'button') score += 20;
        if (/(log in|login|sign in|sign-in)/.test(haystack)) score += 50;
        if (button.type === 'submit') score += 10;
        return { button, score };
      })
      .sort((a, b) => b.score - a.score)[0]?.button ?? buttons[0];
    return {
      username: locatorFor(username, 'username'),
      password: locatorFor(password, 'password'),
      submit: locatorFor(submit, 'submit'),
    };
  });
}

function cssEscape(value: string): string {
  return value.replaceAll('\\\\', '\\\\\\\\').replaceAll('"', '\\\\"');
}
`;
}
