import { mkdtemp, readFile, rm, stat } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import { emitJs } from '../src/emit/js.js';
import { emitTs, specFilesFor, specPathFor } from '../src/emit/ts.js';
import type { TathyaConfig } from '../src/config.js';
import type { TestCase } from '../src/mapper.js';

const config: TathyaConfig = {
  baseUrl: 'http://127.0.0.1:8000',
  output: { dir: '', language: 'ts' },
  coverage: 'all',
  mode: 'read-write',
  oracle: { errorSelector: '.invalid-feedback, [role=alert], .text-red-600, x-input-error p' },
  auth: {
    loginPath: '/login',
    roles: [{ name: 'admin', username: 'admin@example.com', password: 'password' }],
  },
  crawl: { maxDepth: 3, maxPages: 100, include: [], exclude: [] },
  data: { fields: {}, defaults: {}, unique: [], duplicates: {}, requiredFields: [], confirmFields: [], faker: { locale: 'en', seed: null } },
  evaluation: { outDir: 'metrics', repeat: 1, manualBaselineSecPerCase: 300, baselineDir: 'tests/manual', faultProject: null, stacks: [], faults: { enabled: true, classes: ['validation', 'authz', 'crud', 'pagination', 'auth'] } },
};

const emptyPage = (url: string, title: string) => ({ url, title, forms: [], links: [], buttons: [], tables: [] });
const noConstraints = { minlength: null, maxlength: null, min: null, max: null, step: null, pattern: null, inputmode: null, accept: null };

const paginationCase: TestCase = {
  kind: 'pagination',
  tier: 'positive',
  title: 'admin /products pagination next -> handled',
  role: 'admin',
  page: emptyPage('/products?page=1', 'Products'),
  pagination: {
    type: 'link',
    label: 'Next',
    locator: { strategy: 'role', value: 'link:Next' },
    ordinal: 0,
    href: '/products?page=2',
    action: 'next',
  },
};

describe('spec layout', () => {
  it('puts every case in a file per category and route shape', () => {
    expect(specPathFor({ kind: 'auth', tier: 'positive', title: 't', role: 'admin', username: 'u', password: 'p', expectSuccess: true })).toBe('auth/login.spec.ts');
    expect(specPathFor(paginationCase)).toBe('pagination/products.spec.ts');
    expect(specPathFor({ kind: 'rbac', tier: 'negative', title: 't', role: 'user', route: '/todos/7/edit?tab=1', expectAllowed: false })).toBe('rbac/todos-id-edit.spec.ts');
    expect(specPathFor({ kind: 'rbac', tier: 'positive', title: 't', role: 'admin', route: '/', expectAllowed: true })).toBe('rbac/root.spec.ts');
    expect(specPathFor({ kind: 'interaction', tier: 'positive', title: 't', role: 'admin', page: emptyPage('/inventory.html', 'Inventory'), interaction: { type: 'link', label: 'Cart', locator: { strategy: 'role', value: 'link:Cart' }, ordinal: 0, href: '/cart.html' } })).toBe('interactions/inventory-html.spec.ts');
  });

  it('always ships the support module and one spec per group', () => {
    const files = specFilesFor([paginationCase], config);

    expect([...files.keys()]).toEqual(['support/tathya.ts', 'pagination/products.spec.ts']);
    expect(files.get('pagination/products.spec.ts')).toContain("from '../support/tathya.js';");
    expect(files.get('pagination/products.spec.ts')).toMatch(/^\/\/ Generated by `tt generate`/);
  });
});

describe('emitTs', () => {
  it('emits auth specs without using role storage state', async () => {
    const dir = await mkdtemp(join(tmpdir(), 'tt-emit-'));
    try {
      const cases: TestCase[] = [
        { kind: 'auth', tier: 'positive', title: 'login admin valid -> success', role: 'admin', username: 'admin@example.com', password: 'password', expectSuccess: true },
        { kind: 'auth', tier: 'negative', title: 'login admin wrong-password -> error', role: 'admin', username: 'admin@example.com', password: 'password-wrong', expectSuccess: false },
      ];

      await emitTs(cases, { ...config, output: { ...config.output, dir } });
      const authSpec = await readFile(join(dir, 'auth', 'login.spec.ts'), 'utf8');
      const support = await readFile(join(dir, 'support', 'tathya.ts'), 'utf8');

      expect(authSpec).toContain('test.use({ storageState: { cookies: [], origins: [] } });');
      expect(authSpec).toContain('test.describe("admin login", () => {');
      expect(authSpec).toContain('test.skip(({ role }) => role !== "admin", "runs under the admin project only");');
      expect(authSpec).toContain('performLogin(page, "admin@example.com", "password")');
      expect(authSpec).toContain('assertLoggedIn(page)');
      expect(authSpec).toContain('assertLoginRejected(page)');

      await emitTs([{
        kind: 'auth', tier: 'positive', title: 'admin logs out', role: 'admin', username: 'admin@example.com', password: 'password', expectSuccess: true,
        logout: {
          page: emptyPage('/dashboard', 'Dashboard'),
          form: { action: '/logout', method: 'POST', crudOp: 'logout', noValidate: false, fields: [], submit: { text: 'Log Out', locator: { strategy: 'role', value: 'button:Log Out' } } },
        },
      }], { ...config, output: { ...config.output, dir } });
      const logoutSpec = await readFile(join(dir, 'auth', 'login.spec.ts'), 'utf8');
      expect(logoutSpec).toContain('test("admin logs out", { tag: ["@positive","@auth","@role:admin","@write"]');
      expect(logoutSpec).toContain('await test.step("Log in as admin", () => app.loginAs("admin"));');
      expect(logoutSpec).toContain('page.locator("form[action$=\\"/logout\\"]")');
      expect(logoutSpec).toContain('await test.step("Expect /dashboard to need a login again", () => assertLoggedOut(page, "/dashboard"));');
      expect(authSpec).not.toContain('storageState/admin.json');
      // Login mechanics live in the support module, not in every spec.
      expect(authSpec).not.toContain('inferLoginControls');
      expect(support).toContain('export async function inferLoginControls');
      expect(support).toContain('await page.goto(loginPath);');
      expect(support).toContain('const loginPath = "/login";');
      expect(support).toContain('export const test = base.extend<{ role: string; app: App }>');
    } finally {
      await rm(dir, { recursive: true, force: true });
    }
  });

  it('fills valid create forms with runtime faker values and asserts the variable', async () => {
    const dir = await mkdtemp(join(tmpdir(), 'tt-emit-faker-'));
    try {
      const localConfig: TathyaConfig = {
        ...config,
        output: { ...config.output, dir },
        data: { ...config.data, faker: { locale: 'en', seed: 99 } },
      };
      const titleField = {
        name: 'title',
        type: 'text',
        label: 'Title',
        required: true,
        constraints: { ...noConstraints, maxlength: 255 },
        options: null,
        nameHints: [] as string[],
        locator: { strategy: 'label' as const, value: 'Title' },
      };
      const form = {
        action: '/todos',
        method: 'POST' as const,
        crudOp: 'create' as const,
        noValidate: true,
        fields: [titleField],
        submit: { text: 'Create', locator: { strategy: 'role' as const, value: 'button:Create' } },
      };
      const cases: TestCase[] = [
        {
          kind: 'form',
          tier: 'positive',
          title: 'admin /todos create - valid -> success',
          role: 'admin',
          page: emptyPage('/todos/create', 'Create Todo'),
          form,
          targetField: null,
          variant: { kind: 'positive', name: 'valid', value: '', outcome: 'success' },
          values: { title: { kind: 'runtime', expr: 'faker.lorem.words({ min: 2, max: 4 })' } },
        },
      ];

      await emitTs(cases, localConfig);
      const formsSpec = await readFile(join(dir, 'forms', 'todos-create.spec.ts'), 'utf8');

      expect(formsSpec).toContain("import { faker } from '@faker-js/faker';");
      expect(formsSpec).toContain('test.beforeAll(() => { faker.seed(99); });');
      expect(formsSpec).toContain('test.describe("admin · /todos/create", () => {');
      expect(formsSpec).toContain('test.describe("\\"Create\\" form → POST /todos", () => {');
      expect(formsSpec).toContain('const f_title = faker.lorem.words({ min: 2, max: 4 });');
      expect(formsSpec).toContain(".fill(f_title);");
      expect(formsSpec).toContain("await test.step('Fill the form', async () => {");
      expect(formsSpec).toContain("await test.step('Submit', async () => {");
      expect(formsSpec).toContain("await test.step(\"Expect the submission to succeed\", async () => {");
      expect(formsSpec).toContain('await expect(page.getByText(f_title).first()).toBeVisible();');
      // Tags and annotations carry the manifest classification.
      expect(formsSpec).toContain('{ tag: ["@positive","@crud","@role:admin","@write"], annotation: [{"type":"tier","description":"positive"},{"type":"category","description":"crud"},{"type":"route","description":"/todos/create"}] }');
    } finally {
      await rm(dir, { recursive: true, force: true });
    }
  });

  it('uploads an in-memory fixture for file inputs instead of filling them', async () => {
    const dir = await mkdtemp(join(tmpdir(), 'tt-emit-file-'));
    try {
      const avatar = {
        name: 'avatar', type: 'file', label: 'Avatar', required: true, constraints: { ...noConstraints, accept: 'image/*' },
        options: null, nameHints: [], locator: { strategy: 'label' as const, value: 'Avatar' },
      };
      const form = { action: '/profile', method: 'POST' as const, crudOp: 'update' as const, noValidate: true, fields: [avatar], submit: { text: 'Save', locator: { strategy: 'role' as const, value: 'button:Save' } } };
      const cases: TestCase[] = [
        {
          kind: 'form', tier: 'positive', title: 'admin · /profile · "Save" form → POST /profile · submits valid data successfully', role: 'admin',
          page: emptyPage('/profile', 'Profile'), form, targetField: null,
          variant: { kind: 'positive', name: 'valid', value: '', outcome: 'success' },
          values: { avatar: { kind: 'literal', value: 'image/png' } },
        },
        {
          kind: 'form', tier: 'negative', title: 'admin · /profile · "Save" form → POST /profile · avatar rejects an empty value', role: 'admin',
          page: emptyPage('/profile', 'Profile'), form, targetField: avatar,
          variant: { kind: 'negative', name: 'required-empty', value: '', outcome: 'error' },
          values: { avatar: { kind: 'literal', value: '' } },
        },
      ];

      await emitTs(cases, { ...config, output: { ...config.output, dir } });
      const spec = await readFile(join(dir, 'forms', 'profile.spec.ts'), 'utf8');
      const support = await readFile(join(dir, 'support', 'tathya.ts'), 'utf8');

      expect(spec).toContain("import { test, expect, uploadFixture, expectQueryEcho, expectStateFlipped } from '../support/tathya.js';");
      expect(spec).toContain('await page.getByLabel("Avatar", { exact: true }).setInputFiles(uploadFixture("image/png"));');
      expect(spec).toContain('await page.getByLabel("Avatar", { exact: true }).setInputFiles([]);');
      expect(spec).not.toContain('.fill("image/png")');
      expect(support).toContain('export function uploadFixture(mimeType: string)');
    } finally {
      await rm(dir, { recursive: true, force: true });
    }
  });

  it('asserts the query echo of GET forms, the state flip of toggles, and where links land', async () => {
    const dir = await mkdtemp(join(tmpdir(), 'tt-emit-oracles-'));
    try {
      const search = { name: 'search', type: 'search', label: 'Search', required: false, constraints: noConstraints, options: null, nameHints: [], locator: { strategy: 'label' as const, value: 'Search' } };
      const status = { ...search, name: 'status', type: 'select', label: 'Status', options: [{ value: 'open', label: 'Open' }], locator: { strategy: 'label' as const, value: 'Status' } };
      const cases: TestCase[] = [
        {
          kind: 'form', tier: 'positive', title: 'admin · /todos · "Apply" form → GET /todos · submits valid data successfully', role: 'admin',
          page: emptyPage('/todos', 'Todos'),
          form: { action: '/todos', method: 'GET', crudOp: 'unknown', noValidate: false, fields: [search, status], submit: { text: 'Apply', locator: { strategy: 'role', value: 'button:Apply' } } },
          targetField: null, variant: { kind: 'positive', name: 'valid', value: '', outcome: 'success' },
          values: { search: { kind: 'runtime', expr: 'faker.lorem.word()' }, status: { kind: 'literal', value: 'open' } },
        },
        {
          kind: 'form', tier: 'positive', title: 'admin · /todos · "Mark done" form → POST /todos/1/toggle · submits successfully', role: 'admin',
          page: emptyPage('/todos', 'Todos'),
          form: { action: '/todos/1/toggle', method: 'POST', crudOp: 'update', noValidate: false, fields: [], submit: { text: 'Mark done', locator: { strategy: 'role', value: 'button:Mark done' } } },
          targetField: null, variant: { kind: 'positive', name: 'valid', value: '', outcome: 'success' }, values: {},
        },
        {
          kind: 'interaction', tier: 'positive', title: 'admin · /dashboard · follows the "Todos" link to /todos', role: 'admin',
          page: emptyPage('/dashboard', 'Dashboard'),
          interaction: { type: 'link', label: 'Todos', locator: { strategy: 'role', value: 'link:Todos' }, ordinal: 0, href: '/todos?status=done' },
        },
        {
          kind: 'interaction', tier: 'positive', title: 'admin · /dashboard · follows the "Log Out" link to /logout', role: 'admin',
          page: emptyPage('/dashboard', 'Dashboard'),
          interaction: { type: 'link', label: 'Log Out', locator: { strategy: 'role', value: 'link:Log Out' }, ordinal: 0, href: '/logout' },
        },
      ];

      await emitTs(cases, { ...config, output: { ...config.output, dir } });
      const forms = await readFile(join(dir, 'forms', 'todos.spec.ts'), 'utf8');
      const links = await readFile(join(dir, 'interactions', 'dashboard.spec.ts'), 'utf8');

      expect(forms).toContain('await expectQueryEcho(page, { "search": f_search, "status": "open" });');
      expect(forms).toContain('await test.step("Expect the filters in the URL", async () => {');
      expect(forms).toContain('const before = await ((await page.locator("form[action$=\\"/todos/1/toggle\\"]").count()) > 0');
      expect(forms).toContain('await expectStateFlipped(page, "form[action$=\\"/todos/1/toggle\\"]", before);');
      expect(links).toContain('await test.step("Expect to land on /todos", () => expect(page).toHaveURL((url) => url.pathname === "/todos"));');
      // Logout links redirect by design: no landing assertion.
      expect(links).not.toContain('Expect to land on /logout');
    } finally {
      await rm(dir, { recursive: true, force: true });
    }
  });

  it('forces invalid select values through a temporary option', async () => {
    const dir = await mkdtemp(join(tmpdir(), 'tt-emit-'));
    try {
      const status = {
        name: 'status', type: 'select', label: 'Status', required: true, constraints: noConstraints,
        options: [{ value: 'open', label: 'Open' }, { value: 'doing', label: 'Doing' }],
        nameHints: [], locator: { strategy: 'label' as const, value: 'Status' },
      };
      const cases: TestCase[] = [
        {
          kind: 'form',
          tier: 'negative',
          title: 'admin /todos create - status invalid-option -> error',
          role: 'admin',
          page: emptyPage('/todos/create', 'Create Todo'),
          form: { action: '/todos', method: 'POST', crudOp: 'create', noValidate: true, fields: [status], submit: { text: 'Create', locator: { strategy: 'role', value: 'button:Create' } } },
          targetField: status,
          variant: { kind: 'negative', name: 'invalid-option', value: '__invalid_option__', outcome: 'error', forceInvalidOption: true },
          values: { status: { kind: 'literal', value: '__invalid_option__' } },
        },
      ];

      await emitTs(cases, { ...config, output: { ...config.output, dir } });
      const formsSpec = await readFile(join(dir, 'forms', 'todos-create.spec.ts'), 'utf8');

      expect(formsSpec).toContain('HTMLSelectElement');
      expect(formsSpec).toContain('document.createElement(\'option\')');
      expect(formsSpec).toContain('element.value = value;');
      expect(formsSpec).not.toContain('selectOption("__invalid_option__")');
      expect(formsSpec).toContain('{"type":"constraintKind","description":"option"}');
      expect(formsSpec).toContain("await test.step(\"Expect a validation error\", async () => {");
    } finally {
      await rm(dir, { recursive: true, force: true });
    }
  });

  it('clears required selects and radio groups for blank negatives', async () => {
    const dir = await mkdtemp(join(tmpdir(), 'tt-emit-'));
    try {
      const status = {
        name: 'status', type: 'select', label: 'Status', required: true, constraints: noConstraints,
        options: [{ value: 'open', label: 'Open' }, { value: 'doing', label: 'Doing' }],
        nameHints: [], locator: { strategy: 'label' as const, value: 'Status' },
      };
      const choice = {
        name: 'choice', type: 'radio', label: 'Choice', required: true, constraints: noConstraints,
        options: [{ value: 'one', label: 'One' }, { value: 'two', label: 'Two' }],
        nameHints: [], locator: { strategy: 'label' as const, value: 'Choice' },
      };
      const submit = { text: 'Create', locator: { strategy: 'role' as const, value: 'button:Create' } };
      const cases: TestCase[] = [
        {
          kind: 'form', tier: 'negative', title: 'admin /todos create - status required-empty -> error', role: 'admin',
          page: emptyPage('/todos/create', 'Create Todo'),
          form: { action: '/todos', method: 'POST', crudOp: 'create', noValidate: true, fields: [status], submit },
          targetField: status,
          variant: { kind: 'negative', name: 'required-empty', value: '', outcome: 'error' },
          values: { status: { kind: 'literal', value: '' } },
        },
        {
          kind: 'form', tier: 'negative', title: 'admin /todos create - choice required-empty -> error', role: 'admin',
          page: emptyPage('/todos/create', 'Create Todo'),
          form: { action: '/todos', method: 'POST', crudOp: 'create', noValidate: true, fields: [choice], submit },
          targetField: choice,
          variant: { kind: 'negative', name: 'required-empty', value: '', outcome: 'error' },
          values: { choice: { kind: 'literal', value: '' } },
        },
      ];

      await emitTs(cases, { ...config, output: { ...config.output, dir } });
      const formsSpec = await readFile(join(dir, 'forms', 'todos-create.spec.ts'), 'utf8');

      expect(formsSpec).toContain('selectedIndex = -1');
      expect(formsSpec).toContain('evaluateAll((elements) =>');
      expect(formsSpec).toContain('element.checked = false;');
    } finally {
      await rm(dir, { recursive: true, force: true });
    }
  });

  it('emits interaction specs with duplicate locator ordinals and the shared login fixture', async () => {
    const dir = await mkdtemp(join(tmpdir(), 'tt-emit-'));
    try {
      const cases: TestCase[] = [
        {
          kind: 'interaction',
          tier: 'positive',
          title: 'admin /inventory.html button Add to cart -> handled',
          role: 'admin',
          page: emptyPage('/inventory.html', 'Inventory'),
          interaction: { type: 'button', label: 'Add to cart', locator: { strategy: 'role', value: 'button:Add to cart' }, ordinal: 1 },
        },
      ];

      await emitTs(cases, { ...config, output: { ...config.output, dir } });
      const interactionsSpec = await readFile(join(dir, 'interactions', 'inventory-html.spec.ts'), 'utf8');

      expect(interactionsSpec).toContain('page.getByRole("button", { name: "Add to cart" }).nth(1)');
      expect(interactionsSpec).toContain('interaction target is not visible');
      expect(interactionsSpec).toContain('await test.step("Log in as admin", () => app.loginAs("admin"));');
      expect(interactionsSpec).toContain('await test.step("Click button \\"Add to cart\\"", () => target.click());');
      expect(interactionsSpec).toContain("await test.step('Expect no server error', () => expectNoServerError(page));");
      expect(interactionsSpec).toContain('tag: ["@positive","@nav","@role:admin","@write"]');
      expect(interactionsSpec).not.toContain('/dashboard');
    } finally {
      await rm(dir, { recursive: true, force: true });
    }
  });

  it('emits rbac specs that delegate allowed/blocked oracles to the support module', async () => {
    const dir = await mkdtemp(join(tmpdir(), 'tt-emit-rbac-'));
    try {
      const cases: TestCase[] = [
        { kind: 'rbac', tier: 'positive', title: 'admin can visit /admin/users -> allowed', role: 'admin', route: '/admin/users', expectAllowed: true },
        { kind: 'rbac', tier: 'negative', title: 'user cannot visit /admin/users?page=2 -> blocked', role: 'user', route: '/admin/users?page=2', expectAllowed: false },
        { kind: 'rbac', tier: 'positive', title: 'standard_user can visit /cart.html -> allowed', role: 'standard_user', route: '/cart.html', expectAllowed: true },
      ];

      await emitTs(cases, { ...config, output: { ...config.output, dir } });
      const adminUsers = await readFile(join(dir, 'rbac', 'admin-users.spec.ts'), 'utf8');
      const cart = await readFile(join(dir, 'rbac', 'cart-html.spec.ts'), 'utf8');
      const support = await readFile(join(dir, 'support', 'tathya.ts'), 'utf8');

      // Both roles that touch /admin/users share one file, each in its own gated group.
      expect(adminUsers).toContain('test.describe("admin · /admin/users", () => {');
      expect(adminUsers).toContain('test.describe("user · /admin/users", () => {');
      expect(adminUsers).toContain('const response = await test.step("Open /admin/users", () => page.goto("/admin/users"));');
      expect(adminUsers).toContain('expectRouteAllowed(page, response, "/admin/users")');
      // Blocked: the query is stripped from the asserted pathname.
      expect(adminUsers).toContain('page.goto("/admin/users?page=2")');
      expect(adminUsers).toContain('expectRouteBlocked(page, response, "/admin/users")');
      expect(cart).toContain('expectRouteAllowed(page, response, "/cart.html")');
      // The oracle logic itself lives once, in the support module.
      expect(support).toContain("expect(await page.locator('a, button, form, select, input').count()).toBeGreaterThan(0);");
      expect(support).toContain('expect([401, 403, 404]).toContain(status);');
      expect(support).toContain('expect(new URL(page.url()).pathname).not.toBe(blockedPath);');
      expect(support).toContain("not.toContainText(/500|server error|exception/i);");
    } finally {
      await rm(dir, { recursive: true, force: true });
    }
  });

  it('emits pagination specs with a web-first landing assertion', async () => {
    const dir = await mkdtemp(join(tmpdir(), 'tt-emit-pagination-'));
    try {
      await emitTs([paginationCase], { ...config, output: { ...config.output, dir } });
      const paginationSpec = await readFile(join(dir, 'pagination', 'products.spec.ts'), 'utf8');

      expect(paginationSpec).toContain('app.loginAs("admin")');
      expect(paginationSpec).toContain('page.getByRole("link", { name: "Next" }).first()');
      expect(paginationSpec).toContain('await test.step("Go to the next page", () => target.click());');
      expect(paginationSpec).toContain('expect(page).toHaveURL((url) => url.pathname + url.search === "/products?page=2")');
    } finally {
      await rm(dir, { recursive: true, force: true });
    }
  });

  it('calls the app reset hook only when the config declares one', async () => {
    const dir = await mkdtemp(join(tmpdir(), 'tt-emit-hooks-'));
    try {
      const cases: TestCase[] = [{ kind: 'rbac', tier: 'positive', title: 'admin can open /todos', role: 'admin', route: '/todos', expectAllowed: true }];

      await emitTs(cases, { ...config, output: { ...config.output, dir } });
      const withoutHook = await readFile(join(dir, 'support', 'tathya.ts'), 'utf8');
      expect(withoutHook).not.toContain('__testing');
      expect(withoutHook).toContain('const resetHook: { method: \'POST\' | \'GET\' | \'DELETE\'; path: string } | null = null;');

      await emitTs(cases, { ...config, output: { ...config.output, dir }, hooks: { reset: { method: 'POST', path: '/__testing/reset' } } });
      const withHook = await readFile(join(dir, 'support', 'tathya.ts'), 'utf8');
      expect(withHook).toContain('= {"method":"POST","path":"/__testing/reset"};');
      expect(withHook).toContain('await page.request.fetch(resetHook.path, { method: resetHook.method });');
    } finally {
      await rm(dir, { recursive: true, force: true });
    }
  });

  it('tags every test @read or @write and emits read-only specs that reuse the session', async () => {
    const dir = await mkdtemp(join(tmpdir(), 'tt-emit-readonly-'));
    try {
      const cases: TestCase[] = [
        paginationCase,
        { kind: 'rbac', tier: 'positive', title: 'admin can open /todos', role: 'admin', route: '/todos', expectAllowed: true },
        {
          kind: 'interaction', tier: 'positive', title: 'admin · /inventory.html · clicks the "Add to cart" button', role: 'admin',
          page: emptyPage('/inventory.html', 'Inventory'),
          interaction: { type: 'button', label: 'Add to cart', locator: { strategy: 'role', value: 'button:Add to cart' }, ordinal: 0 },
        },
      ];

      await emitTs(cases, { ...config, output: { ...config.output, dir }, hooks: { reset: { method: 'POST', path: '/__testing/reset' } } });
      const readWrite = await readFile(join(dir, 'pagination', 'products.spec.ts'), 'utf8');
      const buttons = await readFile(join(dir, 'interactions', 'inventory-html.spec.ts'), 'utf8');
      expect(readWrite).toContain('"@role:admin","@read"]');
      expect(buttons).toContain('"@role:admin","@write"]');
      expect(readWrite).toContain('app.loginAs("admin")');

      await emitTs(cases, { ...config, mode: 'read-only', output: { ...config.output, dir }, hooks: { reset: { method: 'POST', path: '/__testing/reset' } } });
      const readOnly = await readFile(join(dir, 'pagination', 'products.spec.ts'), 'utf8');
      const rbac = await readFile(join(dir, 'rbac', 'todos.spec.ts'), 'utf8');
      const support = await readFile(join(dir, 'support', 'tathya.ts'), 'utf8');
      expect(readOnly).toContain('await test.step("Use the admin session", () => app.ensureLoggedIn("admin"));');
      expect(readOnly).not.toContain('app.loginAs(');
      expect(readOnly).toContain('const opened = await test.step("Open /products?page=1", () => page.goto("/products?page=1"));');
      expect(readOnly).toContain('expectRouteAllowed(page, opened, "/products")');
      expect(rbac).toContain('app.ensureLoggedIn("admin")');
      // The session helper never calls the reset hook, even when one is configured.
      expect(support).toContain('export async function ensureLoggedIn');
      expect(support.slice(support.indexOf('export async function ensureLoggedIn'), support.indexOf('export async function performLogin'))).not.toContain('resetAppData');
    } finally {
      await rm(dir, { recursive: true, force: true });
    }
  });

  it('emits JavaScript specs by transpiling the whole TypeScript tree', async () => {
    const dir = await mkdtemp(join(tmpdir(), 'tt-emit-js-'));
    try {
      const cases: TestCase[] = [
        paginationCase,
        {
          kind: 'interaction',
          tier: 'positive',
          title: 'admin /inventory.html link Cart -> handled',
          role: 'admin',
          page: emptyPage('/inventory.html', 'Inventory'),
          interaction: { type: 'link', label: 'Cart', locator: { strategy: 'role', value: 'link:Cart' }, ordinal: 0, href: '/cart.html' },
        },
      ];

      await emitJs(cases, { ...config, output: { ...config.output, dir, language: 'js' } });

      const support = await readFile(join(dir, 'support', 'tathya.js'), 'utf8');
      const interactionsSpec = await readFile(join(dir, 'interactions', 'inventory-html.spec.js'), 'utf8');
      const paginationSpec = await readFile(join(dir, 'pagination', 'products.spec.js'), 'utf8');

      expect(support).toContain("from '@playwright/test'");
      expect(support).not.toContain('type LoginLocator');
      expect(support).not.toContain(': Promise<void>');
      expect(interactionsSpec).toContain("from '../support/tathya.js'");
      expect(interactionsSpec).toContain('page.getByRole("link", { name: "Cart" }).first()');
      expect(paginationSpec).toContain('page.getByRole("link", { name: "Next" }).first()');
      await expect(stat(`${dir}-ts-tmp`)).rejects.toThrow();
    } finally {
      await rm(dir, { recursive: true, force: true });
    }
  });
});
